# Generated by Django 5.2.8 on 2025-11-16 00:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
