# Generated by Django 5.2.8 on 2025-11-20 06:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_foro_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='foro',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
    ]
