# Generated by Django 5.2.8 on 2025-11-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_alter_actividad_descripcion_alter_foro_descripcion'),
        ('formulario', '0002_formulario_pregunta_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes', to='formulario.formulario'),
        ),
    ]
