# Generated by Django 5.2.8 on 2025-11-27 23:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_componente_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text')),
                ('componente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='contenido.componente')),
            ],
        ),
    ]
