# Generated by Django 5.2.8 on 2025-11-30 00:27

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_examen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('foro', 'Foro'), ('examen', 'Examen'), ('cuestionario', 'Cuestionario'), ('recurso', 'Recurso')], max_length=20),
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text')),
                ('componente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionario', to='contenido.componente')),
            ],
        ),
    ]
