# Generated by Django 5.2.8 on 2025-12-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_alter_componente_tipo_cuestionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='tipo',
            field=models.CharField(choices=[('foro', 'Foro'), ('examen', 'Examen'), ('cuestionario', 'Cuestionario')], max_length=20),
        ),
    ]
