# Generated by Django 5.2.8 on 2025-12-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_alter_componente_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componente',
            old_name='contenido',
            new_name='titulo',
        ),
    ]
