# Generated by Django 5.2.8 on 2025-12-02 22:33

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_rename_contenido_componente_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlosarioGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Recursos del Curso', max_length=200)),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Conceptos Importantes', max_length=200)),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contenido')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloque_apoyo', to='contenido.actividad')),
            ],
        ),
    ]
