# Generated by Django 5.2.8 on 2025-12-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0010_glosarioglobal_bloqueapoyo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='max_intentos',
            field=models.PositiveIntegerField(default=1, verbose_name='Intentos máximos'),
        ),
        migrations.AddField(
            model_name='examen',
            name='max_intentos',
            field=models.PositiveIntegerField(default=1, verbose_name='Intentos máximos'),
        ),
    ]
