# Generated by Django 5.2.8 on 2025-11-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_formulario_pregunta_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='correcta',
            field=models.BooleanField(default=False),
        ),
    ]
