# Generated by Django 5.2.8 on 2025-12-04 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_opcion_correcta'),
        ('intento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='intento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='intento.intento'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='formulario.pregunta'),
        ),
    ]
